### ISSUE TITLE
Nerf Krini's machinegun

### ISSUE THREAD

**Issue by ChristopherS** [ALitttleBitDifferent/AmbientPrologueBugs#17]
**Submitted by:** Zil

Make the attackspeed slower and add some spread to the attack. Also decrease the number of Snowballs thrown.

**Comment by DreamyWings** [comment]
We will see what can be improved. AFter all Combat with Krini must be exciting as well

**Comment by ChristopherS** [comment]
I'll accept it for now, and see what I can do about it. I have to agree with Zileris, that at the moment it's pretty OP

**Comment by ChristopherS** [comment]
This fight is not part of the current version anymore.
