### ISSUE TITLE
View Distance and Fog

### ISSUE THREAD

**Issue by ChristopherS** [ALitttleBitDifferent/AmbientPrologueBugs#25]
Submitted by GhostXb
View Distance and Fog in the first part are rather irritating.

**Comment by DreamyWings** [comment]
I don't get what are you talking about.

**Comment by ChristopherS** [comment]
The fog is rather thick and if you are stuck in there, trying to solve the puzzle, it get's a bit annoying, that you can't see so far.

**Comment by DreamyWings** [comment]
this is a level design problem. I will think about that

**Comment by ChristopherS** [comment]
Issue is outdated, since there will be new levels.
