### ISSUE TITLE
Collision missing

### ISSUE THREAD

**Issue by ChristopherS** [ALitttleBitDifferent/AmbientPrologueBugs#28]
If you try to run around the sides od the building, there are sections which don't exist, so you can just run through.

**Comment by snoopystallion** [comment]
you mean this one?
https://youtu.be/J9J7Px8sqmY?t=8m10s

**Comment by snoopystallion** [comment]
also you are be able to walk right off the edge of the world. all you have to do is start a new game and when the game start. turn right and walk just into the nothingness. then comes the edge. sending you flying forever. wouldnt it be a good thing to make a detection if the player is too low under the actual surface that you get respawned at the last safepoint or startpoint or the nearest solid surface?

**Comment by ChristopherS** [comment]
Since this specific scenario doesn't exist anymore, this issue is outdated.
