### ISSUE TITLE
Camera not centered on Krini during the fight.

### ISSUE THREAD

**Issue by ChristopherS** [ALitttleBitDifferent/AmbientPrologueBugs#37]
The camera turned sideways during the fight. It might have been caused by trying to focus on Krini while at the same time trying to rotate it.

**Comment by snoopystallion** [comment]
well about that... take a look at what happened here. the camera totally glitched out. 
https://drive.google.com/file/d/0B3GDKRv3xN_maGk3aGlBaUY0Qms/view?usp=sharing

but most likely because krini vanished into the ground

**Comment by ChristopherS** [comment]
This fight as well as the this specific camera mechanic are not part of the current game anymore and/or remade.
