### ISSUE TITLE
Jump attack can launch Astrum a good distance

### ISSUE THREAD

**Issue by ChristopherS** [ALitttleBitDifferent/AmbientPrologueBugs#4]
**Submitted by:** Zil
*_How to reproduce: *_unknown

**Comment by ChristopherS** [comment]
What do you mean by Jump attack? Jumping and then leftclick? Because that didn't really launch me...

**Comment by Zileris** [comment]
in the previous closed beta, the jump attacks would move Astrum forward alit more that it should. this was fixed in the new preview.

**Comment by ChristopherS** [comment]
oh good to know. It wasn't marked as fixed on the spreadsheet.
