### ISSUE TITLE
Game slows down considerably when opening krini's cage

### ISSUE THREAD

**Issue by omutant** [ALitttleBitDifferent/AmbientPrologueBugs#45]
When I open Krinita's cage the game slows down to the point of being unplayable.

**Comment by ChristopherS** [comment]
It could be related to the AI actually doing something, though that shouldn't slow down the game to much. What are your specs and framerates before/after opening the cage? Does it happen everytime for you?

**Comment by snoopystallion** [comment]
i made a short recording to test this 
https://youtu.be/r2fL5vNwlMc

and the framerate dont really drop for me

i-7 4930k at 3,9GHz
16GB DDR3 Ram at 1866
GTX 980
running on a samsung ssd 

but i found another glitch? but you'll see XD

and at the end there are some more ground teleporting

**Comment by ChristopherS** [comment]
I also don't see a drop in the FPS...

**Comment by omutant** [comment]
I think I've replicated it, and I found a few things.
1. reloading a save after hitting krini with something like lightning or fire makes the music stutter
2. attacking Krini with lightning before letting her out of the cage gave me a massive frame drop, from 30-40 down to <10

these were on two separate runs.
one where I didn't hit her before letting her out, in which case it only started to stutter after reloading the save.
And one where I played exactly like I did the first time playing the beta, casting lightning on krini before letting her out of the cage.

From this I think it might be a bug with the "DONT HIT KRINI" thing.

**Comment by snoopystallion** [comment]
well i recorded it. and its not really bounded to the opening. its a general issue i guess. 
https://youtu.be/J9J7Px8sqmY
the frame rate drops von 80 to partly under 50. just because reasons. there isnt much happening. i just  casted some spells here and there on the cage of krini. but i am lucky to have a gtx980. so its still playable. but with older gpu, this could be a problem

**Comment by omutant** [comment]
I think it could be something related to the music, since my frame rate dropped to somewhere between 3-5 when I cast lightning and the music bugged out for some reason

**Comment by ChristopherS** [comment]
Since these specific triggers are not in the game anymore, I will close this issue.
