### ISSUE TITLE
Earth Bend One Shot?

### ISSUE THREAD

**Issue by GhostXb** [ALitttleBitDifferent/AmbientPrologueBugs#46]
Sometimes it seems I can finish off the wolf even if it had a lot of health left with the earth bend spell. Also being able to spam it and keep the wolf away seems like a game design flaw, makes it too easy.

**Comment by snoopystallion** [comment]
here is the earth bend one shot and super intense hunter fight
https://youtu.be/9-qvEITejbg?t=5m28s

**Comment by ChristopherS** [comment]
Seems to be a dupplicate of #41
