### ISSUE TITLE
Healing is problematic

### ISSUE THREAD

**Issue by Zileris** [ALitttleBitDifferent/AmbientPrologueBugs#48]
1- it heals so slow, for such a short time its almost useless. Each cast recovers 2 HP. It takes roughly 2 minutes of doing nothing but casting "heal" to recover from almost 0% health. Doesn't sound like much, but that a long time in an adventure game and this is a HUGE turnoff.
Solutions
A:Heal more per cast
B:Heal timer last longer. 
C: A mix of A and B. (enough to make it not a drag to use.)
D: Hold the cast to heal, like the light spell. 
-In addition- make the healing spell upgrade-able, If upgraded spells are going to be implemented.

2- Healing spell is visually intrusive. Makes it hard to see whats going on sometimes.
Solution ideas
-Less emission. particles here and there just to let you know you are healing. Smaller, with a shorter lifespan
-Different visual- a slight color tint or light aura around Astrum (non particle emitter) that is not visually intrusive.

**Comment by ChristopherS** [comment]
I personally didn't find the visuals intrusive.
about the time it takes to heal, I agree with you however. C or D (though D should also be a mix of D and A) sounds like a good solution. Alternativly you could also heal more if you use more C's (the spell) to cast it (C small heal, CC bigger heal and so on). Of course you would also need more Mana the more C's you use.

**Comment by GhostXb** [comment]
You could have a charge mechanism, where you have to charge the heal and you have to stand still, and based on how long you charged, you will get that much health back. Good way to force the player to retreat and find cover to recover.

**Comment by snoopystallion** [comment]
the particles for healing are really annoying in the ruin for example. they almost blind you because it is too much particles going on. the same goes with the leviation in the ruin. really annoying.

**Comment by ChristopherS** [comment]
This issue is outdated as of the new game version since new combat mechanics will be introduced.
