### ISSUE TITLE
Defense- / Fighting-mechanic

### ISSUE THREAD

**Issue by snoopystallion** [ALitttleBitDifferent/AmbientPrologueBugs#49]
**defense mechanic**
there is no decent way to defend yourself. the only thing you can do is running away or teleport away.  and that there isnt a defense mechanic already in there is kinda sad and wrong when you look at her back story. she lives in a world where gets lots of distrust and mocking. and possibly physical bullying. and the only way she can respond to this is with lighning balls, fireballs, over kill earthbending, the force, a flame thrower, a sword? but there isnt a stun spell, a barrier spell, a spell that builds up a wall infront of you out of earth or stuff. or be able to block attacks with your sword.

**focussing the enemy.** 
there should be a button that lets you focus on a target. 

**quick teleport**
what about when you double tap on w,a,s,d, you will teleport in this direction a bit further than jumping in this direction while fighting an enemy or focussing. 

**enemies**
those are simple bullet sponges. you dont need any tactic to defeat them. just choose a spell or attack of your choise and you are good to go. that ok-ish for small mobs. but not for enemies like this hunter. there should be some kind of tactic to defeat them. like: when you fight the hunter, you have to stun or distract him to get to his side, where he has a weak spot to make real damage. or that things like the sword doesnt work at all because the enemie is made of stone or metal or some kind of smoke. same goes for magic attacks, that some enemies are immune to certain attacks

**Comment by ChristopherS** [comment]
1. agree
2. agree
3. disagree, Teleporting is a spell and as such should have to be cast. Though an evade mechanic might be useful
4. The hunter is scheduled for a rewrite. I will think about ways to design the boss fight once most of the bugs are fixed.

**Comment by Zileris** [comment]
The combat needs a solid rework. I'm working on some ideas and I need to discuss it with the head designers.
A major thing to keep in mind is this isn't as much of an action-focused game and we are limited on time. An intricate combat system might be too much for the game at the moment- especially if we are having an intricate spell mechanic.

**Comment by ChristopherS** [comment]
As of the new version of the game this issue is outdated since new combat systems will be introduced.
