### ISSUE TITLE
Is the magic regeneration tied to your framerate?

### ISSUE THREAD

**Issue by omutant** [ALitttleBitDifferent/AmbientPrologueBugs#50]
I regenerate magic way slower than what I've seen in snoopy's videos, and seem to be able to glide for about twice as long.

**Comment by GhostXb** [comment]
That may have something to do with Event Tick. It's a function in UE4 blueprints that call an event every frame. It's useful for things you need to do mulitple times, but it has issues, one being your FPS can change the outcome of game play. I looked up it up and found a thread discussing it.

https://forums.unrealengine.com/showthread.php?3200-Why-people-use-Tick-event-as-ultimate-solution-for-looped-calling

Maybe we can use this as a gameplay mechanic. Want super fast megic regeneration? Buy a super computer and get more FPS! (Terrible idea)

**Comment by ChristopherS** [comment]
I havn't had the time to look into the code, if it's really bound to the Event Tick. What you linked there works for something like machinegunfire. For Magic regen however it get's problematic. Since you don't control it yourself, but have the engine run it in the background more or less the whole time, things get problematic. Unreal likes to throw Infinite Loop errors in these situations. However I will try it out.

**Comment by ChristopherS** [comment]
I just remember that Krini's stamina regeneration is bound to you framerate... The fight might actually get easier the lower you Framerate is...

**Comment by omutant** [comment]
Krini was surprisingly easy to beat for me :D

**Comment by snoopystallion** [comment]
i made a small comparison video with 2 settings 
https://drive.google.com/file/d/0B3GDKRv3xN_mQWh5UEE4dUlJbW8/view?usp=sharing
this shows the regen of krini. this is the same. no matter how high the fps is. 

and on a side note. the game is unplayable with the lowest setting XD you cant even read your journal anymore

**Comment by ChristopherS** [comment]
I am was talking about Krini's stamina, not her Health. the stamina is hidden from the player and used internally to determine if she can run etc. 
Also her stamina regen and Health regen are capped. I currently don't know about her Health regen, but to see a difference in her stamina regen I think you need to get below 20 or 30 FPS.

**Comment by snoopystallion** [comment]
oh i have to cripple my gpu for this XD or omutant should record a video lol 

i just testet her health regen for fun and since this is kinda the issue for this, i gave it a shot lol

**Comment by omutant** [comment]
I can do that :3 one ambient.prologue vid coming up

**Comment by omutant** [comment]
![20160625081123_1](https://cloud.githubusercontent.com/assets/18735561/16355072/9c506908-3aac-11e6-9692-c5259afd1c56.jpg)
![20160625081149_1](https://cloud.githubusercontent.com/assets/18735561/16355073/9c65c938-3aac-11e6-95cb-aeae660da00a.jpg)

ok so I cant record a video, because the video freezes up before I can get anything recorded XD
found one thing tho, the framerate dropped to somewhere between 3-5 when I cast lightning whilst the music was playing, plus the music bugged out.

I've included two screencaps, and I've done two tests
I tried running from where I am in SC1 to SC2, and back right after teleporting on the spot.
first time it was with the lowest framerate I could get (3-5), and I could run the entire distance, and still have only regened 80 mana.

Second time it was with a decent framerate 23-27
here I couldn't even reach the switch to krini's cage before my mana was fully regened.

**Comment by snoopystallion** [comment]
so here is the video.
https://drive.google.com/file/d/0B3GDKRv3xN_mYzJWS19KOU9CMHM/view?usp=sharing

on both parts of the video, the settings are all maxed out. and when you have high fps, you can run only a bit into the snow. with low fps, you need to wait a good amount longer that your mana bar refills

**Comment by ChristopherS** [comment]
Fixed in the new version of the game.
