### ISSUE TITLE
getting rid of krini

### ISSUE THREAD

**Issue by snoopystallion** [ALitttleBitDifferent/AmbientPrologueBugs#51]
there are several ways to get rid of krini. 
1. you can levitate her and throw her to the moon (actually just insanely far away but she is still on the map ... somewhere)
   https://youtu.be/J9J7Px8sqmY?t=8m6s
2. you throw her right into the abyss and get rid of her for good
   https://youtu.be/J9J7Px8sqmY?t=9m25s
3. you just grab her in your levitational grasp and go for a walk. this will make krini goes subway and never come back (i guess this is the same as the out of bounce throwing)
   https://youtu.be/J9J7Px8sqmY
   and here again but i stopped walking this time and she came up again
   https://youtu.be/J9J7Px8sqmY?t=8m56s

**Comment by ChristopherS** [comment]
I think this is part of #55. I will close this one with a reference.
