### ISSUE TITLE
earth bending issues

### ISSUE THREAD

**Issue by snoopystallion** [ALitttleBitDifferent/AmbientPrologueBugs#52]
there are some weird effects using the earth bending spell. 
1. you can use him on krini to get her out of the cage. 
   https://youtu.be/J9J7Px8sqmY?t=6m3s
2. you can use it to send her flying once she is out of the cage
   https://youtu.be/J9J7Px8sqmY?t=7m3s
3. and you can insta kill enemies when the get trapped by the summoned earth thing and another obstacle. or you might just pushe them somewhere else into the wall or so. have to test this one out some day. 
   https://youtu.be/J9J7Px8sqmY?t=42s
4. you are able to cast the earth bending in the sky?

**Comment by snoopystallion** [comment]
4. you are able to cast the earth bending in the sky.

**Comment by ChristopherS** [comment]
This specific skill is redone and shouldn't pose a problem anymore.
