### ISSUE TITLE
teleporting with sword attack??

### ISSUE THREAD

**Issue by snoopystallion** [ALitttleBitDifferent/AmbientPrologueBugs#54]
this is an odd one. i got it running after i beat the hunter. when i pressed the left mouse button, then i magically teleported into the direction of the puzzle ruin for some reason. so weird... and i was able to do it over and over again.take a look 
https://youtu.be/J9J7Px8sqmY?t=1m29s

**Comment by snoopystallion** [comment]
i guess i know the issue here. when you trigger the fight with krini. but instead of fighting her, you run away. like into the puzzle ruin. so now you are far away from the fight area. and when you know swing your sword, you will get teleported to this area again. i guess this is a bug XD

**Comment by ChristopherS** [comment]
These specific triggers are not in the current version of the game anymore, so this issue is resolved.
