### ISSUE TITLE
spell casting frenzy

### ISSUE THREAD

**Issue by snoopystallion** [ALitttleBitDifferent/AmbientPrologueBugs#58]
well i wanted to stress out the spell casting mechanic. and i wanted to get krinis snowball fighting skills XD
so i became a snowball minigun in the process. since you can cast as many snowballs as you wish. you are only limited by the time and how often you are able to punch the left mouse button. the same goes with the fireballs and lightning attack. but there is a thing with the fireballs and snowballs. they seem to interact with each other. making some of them explode right infront of your face. 

its kinda fun to watch. take a look 
https://drive.google.com/file/d/0B3GDKRv3xN_mNFY4MUFhNEYyaW8/view?usp=sharing

**Comment by ChristopherS** [comment]
concept changed and should fix this issue
